/**
 * Created by Thaddaeus Dahlberg, Software Engineer, University of St. Thomas on 12/7/2022.
 */

public with sharing class EASYPersonalDataTags {
    public String Banner_ID { get; set; }
    public String UGAQUSCHLRS { get; set; }
    public String Applicant_Email { get; set; }
    public String UGAcctClaimTxt { get; set; }
    public String LastTranscript { get; set; }
    public String Course_Pref { get; set; }
    public String Orientation { get; set; }
    public String Housing_Pref { get; set; }
    public String UGFYClass { get; set; }
    public String Documents_Missing { get; set; }
    public String First_Name { get; set; }
    public String Last_Name { get; set; }
}